version: "3"
services:
  db:
    image: postgres
  web:
    build: .
    ports:
      - "3002:3000"
    links:
      - db
    depends_on:
      - db
    environment:
      - SECRET_KEY_BASE=${RAILS_SECRET_KEY_BASE}
