---
# see https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-centos-6

# manually add exclude=postgresql* to [base] and [updates] in /etc/yum.repos.d/CentOS-Base.repo

- name: check if postgres package repo is installed
  shell: rpm -qa pgdg*
  register: package_list
  changed_when: false

- name: download postgres package repo
  when: package_list.stdout.find('pgdg') == -1
  get_url:
    url: '{{ postgres_rpm }}'
    dest: /tmp/postgres-repo.noarch.rpm

- name: install postgres package repo
  when: package_list.stdout.find('pgdg') == -1
  become: yes
  command: rpm -ivh /tmp/postgres-repo.noarch.rpm

- name: ensure correct version of postgres is installed
  yum:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - postgresql{{ postgres_version_no_dot }}-server
    - postgresql-devel

- name: ensure postgres DB is initialized
  command: service postgresql-{{ postgres_version }} initdb
  become: yes
  ignore_errors: yes
  register: initdb_result
  changed_when: initdb_result.stdout.find('Data directory is not empty') == -1

- name: check if postgres is running
  command: service postgresql-{{ postgres_version }} status
  become: yes
  register: db_running_result
  ignore_errors: yes
  changed_when: false

- name: start postgres
  when: db_running_result.stdout.find('running') == -1
  command: service postgresql-{{ postgres_version }} start
  become: yes
