---
- name: list installed ruby versions
  shell: /home/josh/.rbenv/bin/rbenv versions
  register: ruby_version_list
  changed_when: false
  
- name: ensure correct version of ruby is installed
  when: ruby_version_list.stdout.find('{{ ruby_version }}') == -1
  command: /home/josh/.rbenv/bin/rbenv install {{ ruby_version }}

- name: check selected ruby version
  shell: /home/josh/.rbenv/bin/rbenv global
  register: ruby_global_version
  changed_when: false

- name: globally select correct version of ruby
  when: ruby_global_version.stdout.find('{{ ruby_version }}') == -1
  command: /home/josh/.rbenv/bin/rbenv global {{ ruby_version }}

- name: prevent building docs because seriously
  lineinfile:
    dest: /home/josh/.gemrc
    line: 'gem: --no-document'
    create: yes

- name: update rubygems
  command: '/home/josh/.rbenv/shims/gem update --system'
  register: gem_update_result
  changed_when: gem_update_result.stdout.find('Aborting') == -1

- name: check if bundler is installed
  shell: 'ls /home/josh/.rbenv/shims/bundle || echo "not found"'
  register: bundler_path
  ignore_errors: yes
  changed_when: false

# `gem` ansible command doesn't seem to update shims
- name: update bundler including shims
  when: bundler_path.stdout.find('bundle') == -1
  command: '/home/josh/.rbenv/shims/gem install bundler'
