---
# see https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-centos-7
- name: update rbenv dependencies
  become: yes
  yum: name={{ item }} state=latest
  with_items:
    - git-core
    - zlib
    - zlib-devel
    - gcc-c++
    - patch
    - readline
    - readline-devel
    - libyaml-devel
    - libffi-devel
    - openssl-devel
    - make
    - bzip2
    - autoconf
    - automake
    - libtool
    - bison
    - curl
    - sqlite-devel

- name: update rbenv
  git:
    repo: git://github.com/sstephenson/rbenv.git
    dest: /home/josh/.rbenv

- name: ensure rbenv is on path 
  lineinfile:
    dest: /home/josh/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: ensure rbenv is enabled
  lineinfile:
    dest: /home/josh/.bash_profile
    line: 'eval "$(rbenv init -)"'

- name: update ruby-build
  git:
    repo: git://github.com/sstephenson/ruby-build.git
    dest: /home/josh/.rbenv/plugins/ruby-build

- name: ensure ruby-build is on path 
  lineinfile:
    dest: /home/josh/.bash_profile
    line: 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"'
